[package]
name = "mg-mdl"
description = "Models (MDL, binary and ASCII) and walkmeshes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
mg-core.workspace = true
thiserror.workspace = true

[lints]
workspace = true
