use crate::{Settings, Severity, check_name, key, parse, validate};
use mg_core::ResType;
use mg_edit::{Command, Edit};
use mg_module::Module;
use serde_json::Value;
use std::fmt::Write;

fn fingerprint(bytes: &[u8]) -> String {
    let mut h = 0xcbf29ce484222325u64;
    for b in bytes {
        h = (h ^ u64::from(*b)).wrapping_mul(0x100000001b3);
    }
    format!("{h:016x}")
}

/// Encode JSON as ASCII, including surrogate pairs. NWScript source has no
/// Unicode encoding contract, while JsonParse understands Unicode escapes.
pub(crate) fn ascii_json(v: &Value) -> String {
    let text = serde_json::to_string(v).unwrap();
    let mut out = String::new();
    for ch in text.chars() {
        if ch.is_ascii() {
            out.push(ch);
        } else {
            for unit in ch.encode_utf16(&mut [0; 2]) {
                write!(out, "\\u{unit:04x}").unwrap();
            }
        }
    }
    out
}

pub(crate) fn literal(s: &str) -> String {
    serde_json::to_string(s).unwrap()
}

pub(crate) fn json_string(out: &mut String, variable: &str, v: &Value) {
    writeln!(out, "    string {variable} = \"\";").unwrap();
    // Small literals avoid NWScript token limits. Splitting may occur inside
    // a JSON escape: concatenation restores it before JsonParse is called.
    for chunk in ascii_json(v).as_bytes().chunks(512) {
        writeln!(out, "    {variable} += {};", literal(std::str::from_utf8(chunk).unwrap()))
            .unwrap();
    }
}

pub fn opener_source(name: &str, window: &Value, settings: &Settings) -> Result<String, String> {
    check_name(name)?;
    let window_id = crate::actions::string_expr(settings.window_id.as_deref().unwrap_or(name));
    let mut out = format!(
        "// Generated by Moonglow NUI. Regeneration protects manual changes.\n// Include {name}_o in your own script and call Open_{name}(oPlayer).\n// Choose the player and triggering event in that script; this file has no main.\nvoid Open_{name}(object oPlayer)\n{{\n    if (!GetIsPC(oPlayer)) return;\n"
    );
    if settings.from_resref {
        writeln!(
            out,
            "    int nToken = NuiCreateFromResRef(oPlayer, \"{name}\", {window_id}, \"{name}_e\");"
        )
        .unwrap();
    } else {
        json_string(&mut out, "sLayout", window);
        writeln!(
            out,
            "    int nToken = NuiCreate(oPlayer, JsonParse(sLayout), {window_id}, \"{name}_e\");"
        )
        .unwrap();
    }
    out.push_str("    if (nToken <= 0) return;\n");
    for (i, (bind, b)) in settings.bindings.iter().enumerate() {
        let var = format!("sBind{i}");
        // Names can also be non-ASCII. Decode them through JSON at runtime.
        json_string(&mut out, &format!("sName{i}"), &Value::String(bind.clone()));
        json_string(&mut out, &var, &b.value);
        writeln!(
            out,
            "    NuiSetBind(oPlayer, nToken, JsonGetString(JsonParse(sName{i})), JsonParse({var}));"
        )
        .unwrap();
    }
    // Watches are enabled only after *all* initial values are installed.
    for (i, (bind, b)) in settings.bindings.iter().enumerate() {
        if b.watch || settings.actions.iter().any(|a| a.event == "watch" && a.element == *bind) {
            writeln!(
                out,
                "    NuiSetBindWatch(oPlayer, nToken, JsonGetString(JsonParse(sName{i})), TRUE);"
            )
            .unwrap();
        }
    }
    out.push_str("}\n");
    Ok(out)
}

pub(crate) const EVENTS: &str =
    "// Generated NUI events. No actions configured.\nvoid main()\n{\n}\n";

// Recognize only the exact old generated template when upgrading an owned script.
const LEGACY_EVENTS: &str = "// Moonglow NUI event script: preserved on regeneration; edit this file.\nvoid main()\n{\n    object oPlayer = NuiGetEventPlayer();\n    int nToken = NuiGetEventWindow();\n    string sType = NuiGetEventType();\n    string sElement = NuiGetEventElement();\n    if (sType == \"click\" && sElement == \"mg_close\")\n        NuiDestroy(oPlayer, nToken);\n    // Add click/watch handling here. List events expose NuiGetEventArrayIndex().\n}\n";

/// Includes event metadata and manual event edits in the editor's build status.
pub fn is_current(module: &Module, name: &str, window: &Value, settings: &Settings) -> bool {
    let Ok(opener) = opener_source(name, window, settings) else { return false };
    let Ok(events) = crate::actions::event_source(settings) else { return false };
    module.get(&key(&format!("{name}_o"), ResType::NSS)) == Some(opener.as_bytes())
        && settings.event_hash.as_deref() == Some(&fingerprint(events.as_bytes()))
        && module
            .get(&key(&format!("{name}_e"), ResType::NSS))
            .is_some_and(|b| settings.compiled_event_hash.as_deref() == Some(&fingerprint(b)))
        && !module.contains(&key(&format!("{name}_o"), ResType::NCS))
        && module.contains(&key(&format!("{name}_e"), ResType::NCS))
}

/// Prepare the entire change before touching the module. The official
/// compiler resolves module includes first, then the current game's resources.
/// Existing event code is retained and recompiled. An edited opener is an
/// explicit conflict, never silently overwritten. Undo restores all resources.
pub fn generate(
    module: &Module,
    name: &str,
    mut resolve: impl FnMut(&str, ResType) -> Option<Vec<u8>>,
) -> Result<Command, String> {
    check_name(name)?;
    let jui = key(name, ResType::JUI);
    let txt = key(name, ResType::TXT);
    let window = parse(module.get(&jui).ok_or_else(|| format!("Missing {jui}"))?)?;
    let mut settings = match module.get(&txt) {
        Some(b) => Settings::parse(b)?,
        None => Settings::default(),
    };
    let errors: Vec<_> = validate(&window, &settings)
        .into_iter()
        .filter(|d| d.severity == Severity::Error)
        .collect();
    if !errors.is_empty() {
        return Err(errors
            .iter()
            .map(|d| format!("{}: {}", d.path, d.message))
            .collect::<Vec<_>>()
            .join("\n"));
    }
    let opener = format!("{name}_o");
    let events = format!("{name}_e");
    let source = opener_source(name, &window, &settings)?;
    if let Some(old) = module.get(&key(&opener, ResType::NSS)) {
        if old != source.as_bytes() && settings.opener_hash.as_deref() != Some(&fingerprint(old)) {
            return Err(format!(
                "{opener}.nss was edited or belongs to another author. Preserve it and choose another NUI resource name before generating."
            ));
        }
    } else if module.contains(&key(&opener, ResType::NCS)) {
        return Err(format!("{opener}.ncs exists without its source"));
    }
    let generated_events = crate::actions::event_source(&settings)?;
    let event_source = match module.get(&key(&events, ResType::NSS)) {
        Some(b) => {
            if settings.opener_hash.is_none() {
                return Err(format!(
                    "{events}.nss already exists and is not associated with this NUI project"
                ));
            }
            if b == EVENTS.as_bytes()
                || b == LEGACY_EVENTS.as_bytes()
                || settings.event_hash.as_deref() == Some(&fingerprint(b))
            {
                generated_events.as_bytes().to_vec()
            } else if settings.actions.is_empty()
                || settings.event_hash.as_deref() == Some(&fingerprint(generated_events.as_bytes()))
            {
                b.to_vec()
            } else {
                return Err(format!(
                    "{events}.nss was edited. Preserve your event code before changing generated actions."
                ));
            }
        }
        None => {
            if module.contains(&key(&events, ResType::NCS)) {
                return Err(format!("{events}.ncs exists without its source"));
            }
            generated_events.as_bytes().to_vec()
        }
    };
    let mut edits = Vec::new();
    for (n, src) in [(&opener, source.as_bytes()), (&events, event_source.as_slice())] {
        // Validate the include's callable function with the installed compiler.
        // This temporary entry point is never stored or attached to the module.
        let validation_name = "__nui_validate";
        let validation_source =
            format!("#include \"{opener}\"\nvoid main() {{ Open_{name}(OBJECT_SELF); }}\n");
        let mut compiler = mg_script::Compiler::new(|asked, ty| {
            if ty == ResType::NSS {
                if n == &opener && asked.eq_ignore_ascii_case(validation_name) {
                    return Some(validation_source.as_bytes().to_vec());
                }
                if asked.eq_ignore_ascii_case(&opener) {
                    return Some(source.as_bytes().to_vec());
                }
                if asked.eq_ignore_ascii_case(&events) {
                    return Some(event_source.clone());
                }
            }
            mg_resman::ResKey::parse(asked, ty)
                .and_then(|k| module.get(&k))
                .map(<[u8]>::to_vec)
                .or_else(|| resolve(asked, ty))
        });
        let compiled = compiler
            .compile(if n == &opener { validation_name } else { n })
            .map_err(|e| e.to_string())?;
        if compiled.ncs.is_empty() {
            return Err(format!("{n}: compiler did not produce bytecode"));
        }
        edits.push(Edit::SetResource { key: key(n, ResType::NSS), data: Some(src.to_vec()) });
        // Remove a stale executable from the old generated opener atomically.
        // User-edited sources have already been rejected above; Undo restores it.
        edits.push(Edit::SetResource {
            key: key(n, ResType::NCS),
            data: (n != &opener).then_some(compiled.ncs),
        });
        // An old debug map no longer describes this bytecode.
        if module.contains(&key(n, ResType::NDB)) {
            edits.push(Edit::SetResource { key: key(n, ResType::NDB), data: None });
        }
    }
    settings.opener_hash = Some(fingerprint(source.as_bytes()));
    settings.event_hash = Some(fingerprint(generated_events.as_bytes()));
    settings.compiled_event_hash = Some(fingerprint(&event_source));
    edits.push(Edit::SetResource { key: txt, data: Some(settings.bytes()) });
    edits.retain(|e| match e {
        Edit::SetResource { key, data } => module.get(key) != data.as_deref(),
        _ => true,
    });
    Ok(Command::new(format!("Generate NUI {name}"), edits))
}
