//! Prints the GFF schema observed in the shipped game data: for each file
//! type, every field path with its types, how many files have it, and the
//! struct ids seen for structs and list items.
//!
//!     cargo run -p mg-corpus-tests --release --example observed_schema > docs/research/gff-observed-schema.md

use std::collections::{BTreeMap, BTreeSet};

use mg_erf::Erf;
use mg_gff::{Gff, Struct, Value};
use mg_key::KeySet;

#[derive(Default)]
struct PathInfo {
    types: BTreeMap<&'static str, usize>,
    files: usize,
    struct_ids: BTreeSet<u32>,
}

#[derive(Default)]
struct TypeInfo {
    files: usize,
    paths: BTreeMap<String, PathInfo>,
}

/// The time now, as frontmatter gives it: `2026-10-04T06:00:00Z`.
fn utc_now() -> String {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |d| d.as_secs() as i64);
    // Days since 1970-03-01 of a 400-year cycle to a civil date.
    let (days, rest) = (secs.div_euclid(86_400) + 719_468, secs.rem_euclid(86_400));
    let (era, doe) = (days.div_euclid(146_097), days.rem_euclid(146_097));
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let (day, month) = (doy - (153 * mp + 2) / 5 + 1, if mp < 10 { mp + 3 } else { mp - 9 });
    let year = yoe + era * 400 + i64::from(month <= 2);
    format!(
        "{year:04}-{month:02}-{day:02}T{:02}:{:02}:{:02}Z",
        rest / 3600,
        rest % 3600 / 60,
        rest % 60
    )
}

fn walk(s: &Struct, prefix: &str, info: &mut TypeInfo, seen: &mut BTreeSet<String>) {
    for f in &s.fields {
        let path = format!("{prefix}{}", f.label);
        let p = info.paths.entry(path.clone()).or_default();
        *p.types.entry(f.value.field_type().json_name()).or_default() += 1;
        if seen.insert(path.clone()) {
            p.files += 1;
        }
        match &f.value {
            Value::Struct(c) => {
                p.struct_ids.insert(c.id);
                walk(c, &format!("{path}/"), info, seen);
            }
            Value::List(items) => {
                for c in items {
                    if p.struct_ids.len() < 64 {
                        p.struct_ids.insert(c.id);
                    }
                }
                for c in items {
                    walk(c, &format!("{path}[]/"), info, seen);
                }
            }
            _ => {}
        }
    }
}

fn main() {
    let root = mg_testkit::nwn_root().expect("no game install (set NWN_ROOT)");
    let mut by_type: BTreeMap<String, TypeInfo> = BTreeMap::new();
    let mut add = |bytes: &[u8]| {
        let Ok(g) = Gff::read(bytes) else { return };
        let info = by_type.entry(g.file_type_str()).or_default();
        info.files += 1;
        walk(&g.root, "", info, &mut BTreeSet::new());
    };
    for key in ["nwn_base.key", "nwn_retail.key"] {
        let ks = KeySet::open(&root.join("data").join(key), &root).unwrap();
        for e in ks.table.entries.iter().filter(|e| e.restype.is_gff()) {
            add(ks.data(e).unwrap());
        }
    }
    let mut archives = mg_testkit::bundled_modules(&root);
    archives.extend(mg_testkit::bundled_haks(&root));
    for a in &archives {
        let data = std::fs::read(a).unwrap();
        let erf = Erf::read(&data).unwrap();
        for e in erf.entries.iter().filter(|e| e.restype.is_gff()) {
            add(&erf.data(e).unwrap());
        }
    }

    // docs/ is an Open Knowledge Format bundle: the schema is a concept in
    // it, so it opens with frontmatter.
    println!("---");
    println!("type: Reference");
    println!("title: GFF schema observed in the shipped game data");
    println!(
        "description: Every GFF field path seen in the shipped game data (the base game's keys \
         and the shipped modules and haks), per file type, with its GFF types, the share of \
         files that have it and the struct ids seen. Generated by observed_schema.rs."
    );
    println!("tags: [gff, schema, fields, generated]");
    println!("generated: {{ by: process:observed-schema, at: {} }}", utc_now());
    println!("sources:");
    println!("  - id: game-data");
    println!(
        "    resource: The GFF files of the installed game (NWN:EE) - base-game keys and the \
         shipped modules and haks; read by crates/mg-corpus-tests/examples/observed_schema.rs"
    );
    println!("    title: Shipped game data");
    println!("---\n");
    println!("# GFF schema observed in the shipped game data\n");
    println!("Generated by `crates/mg-corpus-tests/examples/observed_schema.rs` from the base");
    println!(
        "game's keys and the {} shipped modules and haks. For each file type: every field",
        archives.len()
    );
    println!("path (`List[]/Field` for list items), its GFF types with occurrence counts, the");
    println!("share of files that have it, and the struct ids seen (first 64 for lists).\n");
    for (ty, info) in &by_type {
        println!("## {ty} ({} files)\n", info.files);
        println!("| Path | Types | Files | Struct ids |");
        println!("| --- | --- | --- | --- |");
        for (path, p) in &info.paths {
            let types: Vec<String> = p.types.iter().map(|(t, n)| format!("{t} ×{n}")).collect();
            let ids = if p.struct_ids.is_empty() {
                String::new()
            } else if p.struct_ids.len() > 8 {
                format!(
                    "{} ids, {}..{}",
                    p.struct_ids.len(),
                    p.struct_ids.first().unwrap(),
                    p.struct_ids.last().unwrap()
                )
            } else {
                p.struct_ids
                    .iter()
                    .map(|i| if *i == u32::MAX { "-1".to_string() } else { i.to_string() })
                    .collect::<Vec<_>>()
                    .join(", ")
            };
            let pct = 100.0 * p.files as f64 / info.files as f64;
            println!("| `{path}` | {} | {pct:.0}% | {ids} |", types.join(", "));
        }
        println!();
    }
}
